<style>
	.searchlistbox {
		display: block;
		max-width: 100%;
		padding: 0.1em 10px;
		color: #212529;
		background-color: #fff;
		background-clip: padding-box;
		border: 1px solid #ced4da;
		-webkit-appearance: none;
		-moz-appearance: none;
		appearance: none;
		border-radius: .25rem;
		transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out
	}
</style>
<? 
if ($_POST['type'] != '') { ?>
	<? include "connection.php"; ?>

	<label for="joinnbufc_register_school" class="form-label">โรงเรียน</label>

	<input list="ShowDataList" required="data-value" class="form-control" id="joinnbufc_register_school" name="joinnbufc_register_school" value="<?=$_SESSION['openhouse_register_school'];?>">

		<datalist id="ShowDataList">
			<? $sql = "select * from school";
			if($_POST['type'] == 'ม.6'){$sql.=' where schooltype_id = 1';}
			if($_POST['type'] == 'ปวช.3'){$sql.=' where schooltype_id = 2';}
			$sql.="  order by school_name";
			$sth = $pdo->prepare($sql);
			$sth->execute();
			foreach ($sth as $school) {
			?>
				<option value="<?= $school['school_name']; ?>">
				<? } ?>

		</datalist>


<? } else { ?>
	<label for="joinnbufc_register_school" class="form-label">โรงเรียน</label>

<select name="joinnbufc_register_school" required class="form-control" id="joinnbufc_register_school">
	<option value="">กรุณาเลือกระดับการศึกษาก่อน.</option>
  
</select>
<? } ?>


<!-- Search Select -->
<script type="text/javascript" src="searchselect/jquery.searchabledropdown-1.0.8.min.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		$(".searchlistbox").searchable({
			maxListSize: 5000, // if list size are less than maxListSize, show them all
			maxMultiMatch: 5000, // how many matching entries should be displayed
			exactMatch: false, // Exact matching on search
			wildcards: true, // Support for wildcard characters (*, ?)
			ignoreCase: true, // Ignore case sensitivity
			latency: 200, // how many millis to wait until starting search
			warnMultiMatch: 'พบ {0} รายการ ...', // string to append to a list of entries cut short by maxMultiMatch 
			warnNoMatch: 'ไม่พบคำที่ค้นหา ...', // string to show in the list when no entries match
			zIndex: 'auto' // zIndex for elements generated by this plugin
		});
	});
</script>